services:
  acta-ui-app-development:
    container_name: acta-ui-app-development
    env_file:
      - .env.development
    build:
      context: ..
      dockerfile: docker/app.Dockerfile
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "100"
    networks:
      - acta-shared-network
      - acta-ui-network
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ..:/app
      - acta-ui-node-modules:/app/node_modules

networks:
  acta-shared-network:
    external: true
    name: acta-shared-network
  acta-ui-network:
    name: acta-ui-network

volumes:
  acta-ui-node-modules:
