export enum Icon8 {
    User = 100,
    StandingMan = 101,
    TallPerson = 102,
    IceHockey = 103,
    Walking = 104,
    PersonLyingDown = 105,
    TrackAndField = 106,
    VolleyballPlayer = 107,
    Gymnastics = 108,
    BattleRopes = 109,
    ArmsUp = 110,
    BenchFitness = 111,
    FigureSkating = 112,
    Traveler = 113,

    Bicycle = 200,
    Fiat500 = 201,
    Bus = 202,
    Truck = 203,
    HomePage = 204,
    Home = 205,
    Company = 206,
    Manufacturing = 207,
    City = 208,
    Apartment = 209,
    Church = 210,
    Library = 211,

    Sun = 300,
    Night = 301,
    Clouds = 302,
    Snow = 303,
    Wind = 304,
    Lake = 305,
    Iceberg = 306,
    Path = 307,
    NationalPark = 308,
    Beach = 309,
    Alps = 310,
    Swamp = 311,

    HeadProfile = 400,
    FemaleBack = 401,
    Pharma = 402,
    ElectricShaver = 403,
    Soap = 404,
    Tooth = 405,
    Lungs = 406,
    Liver = 407,
    Erythrocytes = 408,
    Biotech = 409,
    BodyCells = 410,
    GastricSleeve = 411,

    Water = 500,
    Ingredients = 501,
    Steak = 502,
    RiceBowl = 503,
    SunnySideUpEggs = 504,
    VegetarianFood = 505,
    StrawberryCheesecake = 506,
    Hamburger = 507,
    AppleFruit = 508,
    WineBar = 509,

    Cat = 600,
    Dog = 601,
    RatSilhouette = 602,
    Chicken = 603,
    Pig = 604,
    CowBreed = 605,
    Butterfly = 606,
    FishFood = 607,
    Prawn = 608,

    NoAlcohol = 700,
    NoEnergyDrinks = 701,
    NoCoffee = 702,
    NoFastFood = 703,
    NoSweets = 704,
    NoPhone = 705,
    NoVideoGames = 706,
    NoMoneyWasting = 707,
    NoMasturbation = 708,
}

export const Icon8Names: { [id: number]: string } = {
    [Icon8.RiceBowl]: "rice-bowl.png",
    [Icon8.Lungs]: "lungs.png",
    [Icon8.User]: "user.png",
    [Icon8.Dog]: "dog.png",
    [Icon8.SunnySideUpEggs]: "sunny-side-up-eggs.png",
    [Icon8.Sun]: "sun.png",
    [Icon8.Liver]: "liver.png",
    [Icon8.Apartment]: "apartment.png",
    [Icon8.StandingMan]: "standing-man.png",
    [Icon8.Lake]: "lake.png",
    [Icon8.Home]: "home.png",
    [Icon8.BattleRopes]: "battle-ropes.png",
    [Icon8.TrackAndField]: "track-and-field.png",
    [Icon8.Walking]: "walking.png",
    [Icon8.Erythrocytes]: "erythrocytes.png",
    [Icon8.Butterfly]: "butterfly.png",
    [Icon8.Pharma]: "pharma.png",
    [Icon8.Library]: "library.png",
    [Icon8.VegetarianFood]: "vegetarian-food.png",
    [Icon8.Iceberg]: "iceberg.png",
    [Icon8.Company]: "company.png",
    [Icon8.VolleyballPlayer]: "volleyball-player.png",
    [Icon8.Prawn]: "prawn.png",
    [Icon8.Night]: "night.png",
    [Icon8.Cat]: "cat.png",
    [Icon8.PersonLyingDown]: "person-lying-down.png",
    [Icon8.Biotech]: "biotech.png",
    [Icon8.BenchFitness]: "bench-fitness.png",
    [Icon8.Path]: "path.png",
    [Icon8.Manufacturing]: "manufacturing.png",
    [Icon8.City]: "city.png",
    [Icon8.Hamburger]: "hamburger.png",
    [Icon8.BodyCells]: "body-cells.png",
    [Icon8.Wind]: "wind.png",
    [Icon8.ElectricShaver]: "electric-shaver.png",
    [Icon8.FigureSkating]: "figure-skating.png",
    [Icon8.Tooth]: "tooth.png",
    [Icon8.Gymnastics]: "gymnastics.png",
    [Icon8.RatSilhouette]: "rat-silhouette.png",
    [Icon8.Fiat500]: "fiat-500.png",
    [Icon8.HeadProfile]: "head-profile.png",
    [Icon8.Ingredients]: "ingredients.png",
    [Icon8.NationalPark]: "national-park.png",
    [Icon8.TallPerson]: "tall-person.png",
    [Icon8.Soap]: "soap.png",
    [Icon8.FemaleBack]: "female-back.png",
    [Icon8.Snow]: "snow.png",
    [Icon8.Bus]: "bus.png",
    [Icon8.StrawberryCheesecake]: "strawberry-cheesecake.png",
    [Icon8.Truck]: "truck.png",
    [Icon8.Steak]: "steak.png",
    [Icon8.Traveler]: "traveler.png",
    [Icon8.AppleFruit]: "apple-fruit.png",
    [Icon8.Chicken]: "chicken.png",
    [Icon8.Beach]: "beach.png",
    [Icon8.GastricSleeve]: "gastric-sleeve.png",
    [Icon8.Bicycle]: "bicycle.png",
    [Icon8.Clouds]: "clouds.png",
    [Icon8.Church]: "church.png",
    [Icon8.Pig]: "pig.png",
    [Icon8.WineBar]: "wine-bar.png",
    [Icon8.Swamp]: "swamp.png",
    [Icon8.IceHockey]: "ice-hockey.png",
    [Icon8.Alps]: "alps.png",
    [Icon8.Water]: "water.png",
    [Icon8.ArmsUp]: "arms-up.png",
    [Icon8.HomePage]: "home-page.png",
    [Icon8.FishFood]: "fish-food.png",
    [Icon8.CowBreed]: "cow-breed.png",
    [Icon8.NoAlcohol]: "no-alcohol.png",
    [Icon8.NoEnergyDrinks]: "no-energy-drink.png",
    [Icon8.NoCoffee]: "no-coffee.png",
    [Icon8.NoFastFood]: "no-fast-food.png",
    [Icon8.NoSweets]: "no-sweets.png",
    [Icon8.NoPhone]: "no-phone.png",
    [Icon8.NoVideoGames]: "no-video-games.png",
    [Icon8.NoMoneyWasting]: "no-money-wasting.png",
    [Icon8.NoMasturbation]: "no-masturbation.png",
}